alphagov/pay-cardid

- README.md
- src/main/java/uk/gov/pay/card/app/CardApi.java
- src/main/java/uk/gov/pay/card/db/CardInformationStore.java
- src/main/java/uk/gov/pay/card/db/InfinispanCardInformationStore.java
- src/main/java/uk/gov/pay/card/model/CardInformationResponse.java
- src/main/java/uk/gov/pay/card/resources/CardIdResource.java
- src/main/java/uk/gov/pay/card/service/CardService.java
- src/test/java/uk/gov/pay/card/it/resources/CardIdResourceITest.java
- src/test/java/uk/gov/pay/card/service/CardServiceTest.java
* Integrated the card information store with the service and resource
layers and added the respective unit tests
* Refactored the `CardApi` to manually inject the service and the store
* README.md updated with the expected data file locations
with @PauloPortugal
Run msl up in the cardid project
Access https://cardid.pymnt.localdomain/v1/api/card/[card-number]
> PP-682 Integrating card store with service and resource layers

- src/test/java/uk/gov/pay/card/it/resources/CardIdResourceITest.java
* We still don't have information on the amex BIN ranges.
Therefore we are creating mock data and marking all amex cards
as credit cards.
> PP-682 Adding mocked american express data

- docker-startup.sh
* Please merge https://github.com/alphagov/pay-scripts/pull/233 before merging this.
* As we load all cardid data into memory, the whole data set takes
650MB. With out heap settings the service gets a bit busy with
major GCs. Therefore setting the Xmx and Xms to allocate a sufficient
amount of memory for the service.
branch | PR
------ | ------
increase_memory_limit_for_cardid | https://github.com/alphagov/pay-scripts/pull/233
> PP-682 Configuring heap size

- pom.xml
- src/main/java/uk/gov/pay/card/app/CardApi.java
- src/main/java/uk/gov/pay/card/db/RangeSetCardInformationStore.java
- src/test/java/uk/gov/pay/card/bench/RageSetCardInformationStoreBenchmark.java
- src/test/java/uk/gov/pay/card/db/RangeSetCardInformationStoreTest.java
* While infinispan gives a nice DSL to query for ranges, its also
not the fastest option. Using `RangeSet` to set the ranges and using
a separate ConcurrentHashmap to store card information seem to be
performing faster based on the tests and benchmarks.
* The benchmarks show a 14.910 us/op (average) on the Infinispan approach while
the `RangeSet` based approach comes up with 0.018 us/op (average)
* The `RangeSet` only has the applicable range and the actual data are stored in a
ConcurrentHashmap with the Range as a key. `Range` as a key suffice the requirement
for a key with its implementation of hashcode() and equals() methods.
* Once this is merged, there'll be a separate PR that removes the `InfinispanCardInformationStore`
_Steps to test or …
> Using RangeSet instead of Infinispan

- src/main/java/uk/gov/pay/card/filters/LoggingFilter.java
- src/test/java/uk/gov/pay/card/filters/LoggingFilterTest.java
- To use a dropwizard gauge, the value needs to be provided by something else.
You can't seem to update a gauge manually. It throws an exception if you try to
do that. Therefore using a histogram instead. We will be ignoring, some metrics
emmitted by the histogram though.
with @simad
> PP-1386 Using a histogram instead of a gauge

- pom.xml
- src/test/java/uk/gov/pay/card/it/resources/CardIdResourceITest.java
- Upgraded the following project dependencies to their latest stable version:
- `Dropwizard` from version `0.8.1` to `1.0.6`.
- `guava` from version `19.0` to `21.0`
- `jackson-datatype-jsr310` from version `2.6.7` to `2.8.7`
- `jackson-annotations` from version `2.6.7` to `2.8.7`
- `httpclient` from version `4.5.2` to `4.5.3`
- `jersey-common` from version `2.23.2` to `2.25.1`
- `jersey-media-jaxb` from version `2.23.2` to `2.25.1`
- The latest version of Dropwizard enforces all config values to be resolved at runtime which caused the integration tests to fail because the `ports` weren't specified. To get around the problem the config entries for `ports` have been overwritten in the tests.
`Caused by: …
> PP-1753 Upgraded project dependencies

- pom.xml
This upgrades Jetty from 9.4.10 to 9.4.11
> PP-3937: Upgrade Dropwizard from 1.2.7 to 1.2.8

- src/main/java/uk/gov/pay/card/db/loader/BinRangeDataLoader.java
- src/main/java/uk/gov/pay/card/db/loader/WorldpayPrepaidParser.java
- src/main/java/uk/gov/pay/card/model/CardInformation.java
- src/main/java/uk/gov/pay/card/model/CardInformationResponse.java
- src/main/java/uk/gov/pay/card/model/PrepaidStatus.java
- src/test/java/uk/gov/pay/card/db/loader/BinRangeDataLoaderTest.java
- src/test/java/uk/gov/pay/card/it/resources/CardIdResourceITest.java
- src/test/java/uk/gov/pay/card/model/CardInformationTest.java
- Add `prepaid` to the response. Possible values are `PREPAID`, `NOT_PREPAID`
and `UNKNOWN`.
- Parse the prepaid value from the Worldpay data source and set appropriately
in the response. No implementation for other data sources which will default
the prepaid status to `UNKNOWN`
- Updated and created tests.
> PP-4289_add_prepaid_card_status

- pom.xml
Bring this plugin up to date
Release notes (thanks @alexbishop1 for the digging):
2.4 was released Feb 2012: http://maven.40175.n5.nabble.com/Maven-Jar-Plugin-2-4-Released-td5449745.html
2.5* — http://mail-archives.apache.org/mod_mbox/maven-announce/201406.mbox/%3C20140624102030.A2EEB11E99@minotaur.apache.org%3E
2.6 — http://mail-archives.apache.org/mod_mbox/maven-users/201503.mbox/%3C20150310103739.55BAD174B2@minotaur.apache.org%3E
3.0.0 — http://mail-archives.apache.org/mod_mbox/maven-announce/201605.mbox/%3C20160515194703.8B01819730@minotaur.apache.org%3E
3.1.0 — https://blogs.apache.org/maven/entry/apache-maven-jar-plugin-version
3.1.1 — https://blogs.apache.org/maven/entry/apache-maven-jar-plugin-version1
> PP-4528: Upgrade maven-jar-plugin from 2.4 to 3.1.1

- pom.xml
This service does not call other services, so we have no need for HTTP client
libraries. Remove dropwizard-client and httpclient.
Also, it has no authentication, so we don't need dropwizard-auth
We don't parse timestamps from JSON so we don't need jackson-datatype-jsr310
Our tests don't use com.jayway.jsonpath.matchers.JsonPathMatchers.* so we don't
need json-path-assert
This shrinks the generated .jar by ~10%
> BAU: Remove unused dependencies

- pom.xml
- src/test/java/uk/gov/pay/card/db/loader/WorldpayPrepaidParserTest.java
- src/test/java/uk/gov/pay/card/filters/LoggingFilterTest.java
- src/test/java/uk/gov/pay/card/model/CardTypeTest.java
- src/test/java/uk/gov/pay/card/service/CardServiceTest.java
hamcrest-core is now just 'hamcrest'
hamcrest-library is now just a dummy transitional package to force upgrades for
projects which depend on it (e.g. junit 4.x)
Rewrite a bunch of our tests to not need hamcrest at all
> PP-4574: Upgrade hamcrest to 2.1

- pom.xml
- src/main/java/uk/gov/pay/card/db/loader/WorldpayPrepaidParser.java
- src/test/java/uk/gov/pay/card/filters/LoggingFilterTest.java
* Upgrade JMH benchmarking library to 1.21 (no changes needed)
* Use `startsWith` instead of `containsString` for prefix matching in `LoggingFilterTest`
* Address a couple of warnings from IntelliJ - make `WorldpayPrepaidParser` package private and remove an unused import from `LoggingFilterTest`
I think CI is enough to test this
> BAU: Miscellaneous fixups

- src/main/resources/config/config.yaml
Making the log lines look more like connector's by adding additional info as to what is reported.
This helps in two way: searches are going to return more uniform results, and we will have less noise when looking for errors. For example,level=error will help isolating the logger.error lines rather than lower level ones which simply have the word error in the message
> PP-4602 - change structure of loglines

- pom.xml
- src/main/java/uk/gov/pay/card/resources/HealthCheckResource.java
- src/test/java/uk/gov/pay/card/resources/HealthCheckResourceTest.java
Apply the same change made in pay-direct-debit-connector to adminusers'
healthcheck resource, making it simpler and with a more functional style.
Bring the unit test over from pay-publicapi
> Be more functional in HealthcheckResource

- Dockerfile
Upgrade to our OpenJDK base image based on Alpine 3.9 with OpenJDK 8u201
> PP-4985: Upgrade Alpine & Java

- pom.xml
Added `JAXB API` as dependency as it is removed from Java11 JDK
with @danworth
- CI should pass
> PP-4946 Add `jaxb-api` dependency

- env.sh
cardid does not make use of this environment variable. Remove it.
> PP-4864: Remove reference to CERTS_PATH environment variable

- src/main/java/uk/gov/pay/card/db/RangeSetCardInformationStore.java
- src/main/java/uk/gov/pay/card/service/CardService.java
Add some extra logging in areas of the card information lookup code that look like they would be problematic if assumed preconditions are not met, in the hope this will shed some light on the occasional 500 errors.
> PP-5057 Add some extra logging to track down 500 errors

- README.md
- src/main/resources/config/config.yaml
Document all environment variables used by cardid. Also, take the default port
numbers from the Dockerfile and make them the fallback defaults in the
Dropwizard configuration.
All the documented environment variables, with the exception of JAVA_OPTS, are
interpolated into the Dropwizard configuration. JAVA_OPTS is used by
docker-startup.sh
> PP-5065: Document all environment variables

- Dockerfile
- docker-startup.sh
We try to run our scripts with bash, but bash isn't installed in the container.
We don't actually need bash, so stop asking for it.
Move the default for JAVA_OPTS to the Dockerfile using `ENV` rather than shell
Run java directly from the Dockerfile without a shell script wrapper. This will
have the side benefit of allowing signals to be delivered directly to the
running Java process, so e.g. Ctrl-c will now kill the application.
> RED-46: Remove bash usage from the container

- Dockerfile
Without using the array syntax for `CMD` in the `Dockerfile` we end up
executing `java` with a shell process.
This is unnecessary and undesirable. The shell will absorb the SIGTERM sent to
shut the container down, hiding it from java and leading to an ungraceful
shutdown by the container orchestrator.
Use 'exec' to avoid forking a new process on startup. This will ensure `java`
is process ID 1 within the container and receives signals directly.
> Make java PID 1 in the container

- Dockerfile
Now that Java is running as PID 1, we have solved one problem but created another.
Signals sent to the container will now reach Java correctly instead of being swallowed by bash, but two problems have been created:
* If Java creates any child processes and those processes (or any of their
children) die, Java will be the parent of them and will not know to waitpid()
on them, so they will remain zombies forever. This is not a problem for
cardid as no such child processes should be created, but it's still not really
correct.
* When SIGTERM is sent to the container in order to shut the service down, Java
will exit with an exit status of 143, even though it shut down cleanly. tini
can map this exit status to 0 in order to properly commmunicate the successful
exit to the container orchestrator. …
> Use tini to manage running Java within Docker

- Dockerfile
Now that dependabot can bump the FROM lines of our Dockerfiles, these comments
will become stale and misleading.
> Remove Dockerfile comment

- README.md
- env.sh
- src/main/java/uk/gov/pay/card/app/config/CardConfiguration.java
- src/main/java/uk/gov/pay/card/db/loader/BinRangeDataLoader.java
- src/main/resources/config/config.yaml
- src/test/java/uk/gov/pay/card/bench/RangeSetCardInformationStoreBenchmark.java
- src/test/java/uk/gov/pay/card/db/RangeSetCardInformationStoreTest.java
- src/test/java/uk/gov/pay/card/db/loader/BinRangeDataLoaderTest.java
- src/test/java/uk/gov/pay/card/it/resources/CardIdResourceITest.java
We only ever support loading a single file for each of the BIN range sources, however we specify a directory to load these files from.
If there's not exactly one file in the specified directory we throw an error, so why not specify the filename directly?
Even better, let's make these URLs so that we can potentially download them on startup and don't need to rely on the data being burnt into the container.
> Pull BIN range data from URLs

- src/main/java/uk/gov/pay/card/app/CardApi.java
- src/main/java/uk/gov/pay/card/db/CardInformationStore.java
- src/main/java/uk/gov/pay/card/db/RangeSetCardInformationStore.java
We should not report that we are healthy until all data records have been
loaded into the card information store.
Add a healthcheck to indicate this.
The healthcheck name is 'informationstore'
Retire the 'ping' healthcheck as it now provides no additional value.
> Add a healthcheck for the card information store

- src/main/java/uk/gov/pay/card/service/CardService.java
- src/test/java/uk/gov/pay/card/service/CardServiceTest.java
If you pass a card number with fewer than 11 characters to cardid, it throws an
internal server error.
e.g.
curl -v -X POST -H 'Content-Type: application/json' -d '{ "cardNumber": "4"}' http://localhost:8080/v1/api/card
This is because we call substring(0, 11) on the cardnumber string, which throws
a java.lang.StringIndexOutOfBoundsException on strings shorter than 11
characters.
Make this more robust and return 404 instead.
We already test CardInformationStore quite thoroughly so the only functionality
in CardService we need to test is that the lookup key gets truncated
appropriately.
Move this logic to a separate method and test that specifically.
> REP-190: Stop throwing 500s for short card numbers

- src/main/resources/config/config.yaml
This is used to tell Sentry which stack frames relate to our application
versus those from standard libraries/frameworks. Sentry docs recommend
this is set at
https://docs.sentry.io/clients/java/config/#in-application-stack-frames
This has been set as per the documentation for the sentry dropwizard
appender at https://github.com/dhatim/dropwizard-sentry
> BAU Add stacktraceAppPackage config for Sentry

- pom.xml
- Upgrades dropwizard to v2.0.0
- Dropwizard 2.0.0 upgrade doesn't specify transitive dependency versions anymore https://www.dropwizard.io/en/release-2.0.x/manual/upgrade-notes/upgrade-notes-2_0_x.html
Add parent `dropwizard-dependencies` which has versions of transitive dependencies specified and can be overridden.
We can also include BOM for transitive dependency versions but versions can't be overridden and we may end up with multiple revisions of same library. For example, `jackson-version` current used is `2.10.2` but dropwizard uses `2.10.1`
- Upgraded dropwizard-sentry library too without which builds are failing with error `java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableList org.dhatim.dropwizard.sentry.logging.SentryAppenderFactory.getFilterFactories()'`
- …
> PP-6001 Upgrade dropwizard

- manifest.yml
When running on PaaS Cardid will read the bin range data from a service
named cardid-data. This change adds the env vars which will be set per
space to point to the cardid-data app.
Also, remove defining the route within the manifest since it is set by
terraform when the space is created.
Tested by pushing this manually into our staging-cde space
```
gds5062 > cf push --vars-file /Users/danworth/projects/gds/pay-omnibus/paas/env_variables/staging.yml
state     since                  cpu    memory         disk           details
#0   running   2020-02-07T14:41:04Z   0.0%   420.7M of 1G   260.9M of 1G
```
> PP-6128 Add data locations to manifest

- manifest.yml
- src/main/resources/env-map.yml
Env vars which are specific to cardid and differ by environment
are to be provided via the cardid-secret-service. The mapping
between these vars and their keys within the vars returned by
cardid-secret-service are defined within env-map.yml.
Pushed to staging manually and checked the necessary vars are set
> PP-6127 add cardid-secret-service

- manifest.yml
- src/main/resources/env-map.yml
Set the METRICS_HOST and METRICS_PORT from the app-catalog to send
metrics to the carbon-relay app.
> PP-6254 Add carbon relay

- pom.xml
The pom references the `dropwizard-dependencies` pom v2.0.10 as a parent which
includes an execution rule for `maven-dependency-plugin:analyze-only`
setting the `failOnWarning` to `true` (the default is false). This plugin is
run as part of the `verify` phase. We have undeclared transitive dependencies so the
`analyze-only` goal fails and consquently the build.
This isn't a problem on Jenkins because it runs `mvn package` for cardid
and not `mvn verify` as per all other apps. By fixing this we can test
all java apps in the same manner.
The result of the pom inheritence can be viewed by running `mvn
help:effective-pom`. Earlier versions of the dropwizard pom
used by connector do not introduce the execution rule with
`failOnWarning` true, though this change may be necessary for those …
> PP-6561 Fix mvn verify phase

- pom.xml
This is no longer used as of Jan 2020's
ed4e86891df4afd6a54edfeb4eb43794b845237d
Removing this dependency shrinks the jar from 126MiB to 23MiB by removing the
following transitive dependencies:
- com.amazonaws:aws-xray-recorder-sdk-apache-http
- com.amazonaws:aws-xray-recorder-sdk-aws-sdk
- com.amazonaws:aws-xray-recorder-sdk-aws-sdk-instrumentor
- com.amazonaws:aws-xray-recorder-sdk-core
- com.amazonaws:aws-xray-recorder-sdk-sql-postgres
- io.dropwizard:dropwizard-db
- org.apache.httpcomponents:httpclient
- org.eclipse.persistence:org.eclipse.persistence.jpa
Creating the shaded jar is now much faster for me, reducing the time for 'mvn
clean verify' from 1 minute to ~30 seconds.
_Originally contributed by @rhowe in https://github.com/alphagov/pay-cardid/pull/474._
> Remove uk.gov.pay.utils

- pom.xml
- src/test/java/uk/gov/pay/card/db/RangeSetCardInformationStoreTest.java
- src/test/java/uk/gov/pay/card/db/loader/BinRangeDataLoaderTest.java
- src/test/java/uk/gov/pay/card/db/loader/WorldpayPrepaidParserTest.java
- src/test/java/uk/gov/pay/card/it/resources/CardIdResourceITest.java
- src/test/java/uk/gov/pay/card/model/CardInformationTest.java
- src/test/java/uk/gov/pay/card/model/CardTypeTest.java
- src/test/java/uk/gov/pay/card/resources/HealthCheckResourceTest.java
- src/test/java/uk/gov/pay/card/service/CardServiceTest.java
Replace an implied JUnit 4 with an explicit JUnit 5 Jupiter.
This was mostly straightforward, with the only real change being to adjust
tests for expecting certain exceptions (unfortunately `assertThrows` doesn't
have the facility to match the exception message, just its type).
CardIdResourceITest seems about 5 seconds quicker now.
_Originally contributed by @rhowe in https://github.com/alphagov/pay-cardid/pull/475._
> Convert to JUnit 5

- .secrets.baseline
- src/test/java/uk/gov/pay/card/model/CardTypeTest.java
In JUnit 5, `assertThrows` returns the thrown exception so we can assert on it. This is nicer than using `try`/`catch`.
> BAU — Use assertThrows in tests that assert exception messages

- pom.xml
- logback: our code does not depend on this library. Dropwizard does, however, but dropwizard-core correctly declares a dependency on logback-classic 1.2.3 so we should remove this dependency lest an overly-keen dependency-bumping robot tempt someone into introducing an incompatible version of logback which breaks Dropwizard.
- jaxb: our code does not depend on this library. Dropwizard does, however, but dropwizard-core correctly declares a dependency on logback-classic 1.2.3 so we should remove this dependency lest a overly-keen dependency-bumping robot tempt someone into introducing an incompatible version of logback which breaks Dropwizard.
reference: https://github.com/alphagov/pay-cardid/pull/483 and https://github.com/alphagov/pay-cardid/pull/482
with @rhowe
> BAU remove some unnecessary dependencies

- pom.xml
- src/main/java/uk/gov/pay/card/app/CardApi.java
- As part of the migration from Bintray to Maven Central we must move our coordinates to match the domain we own
- This means that the coordinates of our java packages will now exist under `uk.gov.service.payments` instead of `uk.gov.pay`
- This moves the dependencies of pay-java-commons to maven central from bintray
> PP-7938 Move Package Coordinates

- pom.xml
- pay-java-commons has a dependency on dropwizard-json-logging. Because pay-java-commons uses its own version of dropwizard, the pay-java-commons version and dropwizard dependency versions for the app need to be updated at the same time to build successfully.
- Add a direct dependency on dropwizard-json-logging so we ignore the version in pay-java-commons and use the version consistent with all the other dropwizard modules.
> BAU add dropwizard logging dependency

- src/test/java/uk/gov/pay/card/pact/ConnectorContractTest.java
Alter the `url` parameter for the `@PactBroker` annotation to prefix
with "https://", as the the PACT_BROKER_HOST environment variable will
only provide the host name.
Check whether a PactVerificationContext exists in the setup method and
in the TestTemplate method. This will be null if no pacts are found to
verify. This check could be removed once pacts have been uploaded by
connector.
> PP-9406 Fix contract test runner

- .github/workflows/_run-pact-provider-tests.yml
Located and replaced all usages of set-output commands in our workflows.
> PP-10677: replaced set-output in run-pact-provider-tests.yml

- Dockerfile
- m1/arm64.Dockerfile
Upgrade image to [jdk 11.0.18](https://hub.docker.com/layers/library/eclipse-temurin/11-jre-alpine/images/sha256-4edcb9a82ae75460ff836a63d7bf2d601635233130952083f5bc79bf888ea8ad?context=explore).
See this [adr](https://github.com/alphagov/pay-architecture/blob/main/adr/024-java-base-image-pinning-strategy.md) on why we only specify the major version.
Alpine doesn't provide an ARM variant of [11.0.18_10-jre-alpine](https://hub.docker.com/layers/library/eclipse-temurin/11.0.18_10-jre-alpine/images/sha256-4edcb9a82ae75460ff836a63d7bf2d601635233130952083f5bc79bf888ea8ad?context=explore) so we've used the latest [eclipse-temurin:11-jre](https://hub.docker.com/layers/library/eclipse-temurin/11-jre/images/sha256-dd745f7e5a780d432ea24c9936721271e74853c712a58461c47aecd315ef5701?context=explore).
> PP-10717: Upgrade Docker Java image

- pom.xml
- src/main/java/uk/gov/pay/card/app/CardApi.java
- src/main/java/uk/gov/pay/card/app/config/CardConfiguration.java
- src/main/resources/config/config.yaml
Set up a prometheus metric endpoint /metrics.
Append ECS metadata info (via the PrometheusDefaultLabelSampleBuilder class in pay-java-commons) as default labels.
Analogus to https://github.com/alphagov/pay-connector/pull/4625, which has been tested.
> PP-11223: Set up prometheus metrics

- build-local.sh
- src/main/java/uk/gov/pay/card/app/CardApi.java
Now we don't need to build our default labels in the app (since they are now added by the sidecar) we should remove the default sample builder.
1. Remove default sample builder
2. Update local build script to account for m1 macs, and use the correct container tag
This change has already been rolled out to connector and is working well.
* Introduced any new environment variables / removed existing environment variable
* Added new API / updated existing API definition
> PP-11154: Update initialise prometheus metrics

- m1/arm64.Dockerfile
Run apt-get upgrade for m1 containers (which are ubuntu, not alpine, until we get to java 21)
> PP-11990: Run apt-get upgrade for m1 containers

- src/main/java/uk/gov/pay/card/model/CardInformationRequest.java
- src/test/java/uk/gov/pay/card/it/resources/CardIdResourceITest.java
I used `CARD_RANGE_LENGTH` to define the minimum length for the card number as any card number shorter than this leads to a 404 even if the range is correct.
- Pick a bin range from a CSV that's shorter than the maximum (currently 11) (e.g. `71221111` from src/test/resources/card-id-resource-integration-test/test-bin-ranges.csv)
- Make requests with different numbers of zeros on the end of the prefix e.g. `71221111`, then `712211110`, then `7122111100`
Expectation: The first requests should give validation failures (`422` status code), then when they pass validation they should be found (`200` status code), if you continue to make them longer you'll reach another validation failure (`422` status code).
Current reality: The first requests should give validation failures (`422` status …
> PP-12240: Card length validation matches CARD_RANGE_LENGTH

- .github/dependabot.yml
pact jvm 4.6 requires Java 17. We are running on Java 11. Ignore updates that require Java higher than version 11.
> BAU add dependabot ignore

- .github/workflows/ci-trigger-release.yml
- a called workflow can't have higher permissions than the caller
> PP-12111 match `trigger-release` perms with called workflow

- .github/workflows/ci-trigger-release.yml
- pass pact broker auth secrets to called workflows in `ci-trigger-release`
> PP-12111 pass pact auth secrets to called workflow

- .github/dependabot.yml
Move ignored Maven dependency updates to the right place in the Dependabot configuration.
Also fix problems reported by `yamllint`.
> PP-12520 Move ignored Maven dependency updates in Dependabot config

- .github/workflows/ci-trigger-release.yml
- .github/workflows/post-merge.yml
- Makes post-merge workflow a reusable one as it is being called by ci-trigger-release workflow
> PP-12571 Make post-merge workflow reusable workflow

- .github/dependabot.yml
- .github/workflows/_run-tests.yml
- .github/workflows/codeql.yml
- Dockerfile
- m1/arm64.Dockerfile
- pom.xml
Update pom, dockerfiles, and github actions to use java 21. Where relevant we are also use arm images.
We are upgrading all apps in pay to use Java 21.
> PP-12723: Use Java 21

- README.md
- src/main/resources/config/config.yaml
- src/test/java/uk/gov/pay/card/it/resources/CardIdResourceITest.java
Bind to 127.0.0.1 by default instead of 0.0.0.0
I followed the exact same testing strategy as https://github.com/alphagov/pay-connector/pull/5539 and achieved the same results
> PP-13145: Accept BIND_HOST env var and default to localhost
