- .gitmodules
Tracking master changes for cardid-data
- [] WebOps
> PP-682 tracking master of cardid data

- README.md
* Updating the README with API details and supported data providers.
Read the content and see if it makes sense. This will be updated as we build on the project. But this attempt is to capture the information at the current state.
- [] WebOps
> PP-682 Update README

- src/main/java/uk/gov/pay/card/app/CardApi.java
- src/main/java/uk/gov/pay/card/resources/HealthCheckResource.java
* Exposing the healthchecks on the application ports as well.
Run the application and hit the healthcheck endpoint on the application port. i.e. http://localhost:<application-port>/healthcheck
- [] WebOps
> PP-682 Healthchecks on the applicatino ports

- src/main/java/uk/gov/pay/card/model/CardInformationRequest.java
- src/main/java/uk/gov/pay/card/resources/CardIdResource.java
- src/test/java/uk/gov/pay/card/it/resources/CardIdResourceITest.java
* Having the resource accept GET runs the risk of the card number
being printed in access logs. Therefore making this a POST to avoid it.
> PP-682 Make Resource a POST

- env.sh
- src/main/java/uk/gov/pay/card/db/loader/BinRangeDataLoader.java
Some small fixes to enable better local debugging of cardid.
Fix env.sh's location of the .env file - it's in pay-scripts, not this directory.
Add some more logging for the data file loading process.
> Improve debugging

- src/main/java/uk/gov/pay/card/model/CardInformationResponse.java
- src/main/java/uk/gov/pay/card/resources/CardIdResource.java
* Adding logging for request and response for cardid information
> PP-682 Add Logging

- env.sh
These environment vars need to be different when inside a container or when running on the local machine, so override them in env.sh
> These environment vars need to be different when inside a container

- README.md
* The request to get card information on the endpoint /v1/api/card
is now a POST and not a GET
> Fix out of date cardId readme

- README.md
* The section header was still reporting the request incorrectly as
a GET
> Fix heading of card information API

- pom.xml
- src/main/java/uk/gov/pay/card/app/CardApi.java
- src/main/java/uk/gov/pay/card/filters/LoggingFilter.java
- src/main/java/uk/gov/pay/card/resources/CardIdResource.java
- src/test/java/uk/gov/pay/card/filters/LoggingFilterTest.java
> PP-946 log request id and request times

- Dockerfile
> PP1226 Alpine OpenJDK baselayer

- pom.xml
- src/main/java/uk/gov/pay/card/app/CardApi.java
- src/main/java/uk/gov/pay/card/app/config/CardConfiguration.java
- src/main/resources/config/config.yaml
- We added two environment variables for host and port for
metrics.
- If the variables are not passed, default values are going to
get picked up
with @simad
> PP-1386 - [M&M] - Add dropwizard metrics through graphite UDP reporter

- src/main/java/uk/gov/pay/card/app/CardApi.java
- src/main/java/uk/gov/pay/card/filters/LoggingFilter.java
- src/main/java/uk/gov/pay/card/resources/CardIdResource.java
- src/test/java/uk/gov/pay/card/filters/LoggingFilterTest.java
- Capturing the response time for each resource in a gauge.
with @simad
> PP-1386 Adding response time metrics

- CONTRIBUTING.md
- LICENSE
- README.md
This was already a public repository but didn't have a licence or other supporting information. Unlike the others the readme's API spec is fairly small so I am not moving this out into a docs/ folder yet.
> PP-1739 Open Sourcing

- pom.xml
Revert previous commit pushed by mistake.
> PP-1805 Revert previous commit: Upgraded logback-classic dependency which contains vulnerability

- docker-startup.sh
retain default setting of 1.5GB
> PP-2019 allow JAVA_OPTS to be specified

- src/main/java/uk/gov/pay/card/model/CardInformation.java
- src/test/java/uk/gov/pay/card/db/RangeSetCardInformationStoreTest.java
- src/test/java/uk/gov/pay/card/model/CardInformationTest.java
Added Maestro and Electron
Added explicit mappings for:
* MAESTRO to maestro (worked already, explicitly mapped for clarity in code)
* ELECTRON to visa (also added test for this)
> PP-2411 accept maestro and visa electron

- pom.xml
upgrade jackson-databind to a patched version
> Address CVE-2017-7525

- Jenkinsfile
Deploy parallel cardid ECS and non ECS deployments
> PP-3093 Cardid ECS deployment

- Jenkinsfile
ECS deploys currently a bit borked, so stop doing this
for time being while we sort out
> BAU stop ecs deploys

- Jenkinsfile
Tagging and tests should only occur after ECS is done
solo @tlwr
> BAU: Cardid should deploy ECS

- pom.xml
- upgrade dropwizard to version 1.2.2
- pin jackson to version 2.9.4
> PP-3331 upgrade dropwizard to 1.2.2

- build-local.sh
- pom.xml
Upgrade Dropwizard to 1.2.7 (latest 1.2.x version)
> PP-3930 upgrade dw 127

- Dockerfile
We had extraneous files committed to our data repo. Update to remove them as
they were large and made our containers big.
cardid:latest-master is 192MB
cardid with this change is 143MB
you can review by doing a local build and then running
```
docker run -it govukpay/cardid:latest-master find / |sort > latest-master.list
docker run -it <id of built container> find / |sort > local-build.list
diff -u latest-master.list local-build.list
```
> PP-4388: Update datasets to remove unnecessary files

- pom.xml
> PP-4410: Upgrade jackson from 2.9.6 to 2.9.7

- Dockerfile
- src/test/java/uk/gov/pay/card/bench/RangeSetCardInformationStoreBenchmark.java
- src/test/java/uk/gov/pay/card/filters/LoggingFilterTest.java
- src/test/java/uk/gov/pay/card/it/resources/CardIdResourceITest.java
* Use COPY instead of ADD in Dockerfile
* Make things private which can be in LoggingFilterTest
* Use statically-imported ContentType.JSON in CardIdResourceITest
* Move field declarations to the top of the class in
RangeSetCardInformationStoreBenchmark
> BAU: Cleanups to appease Codacy

- README.md
Codacy picked up some stylistic points regarding our Markdown formatting in
README.md. Address them and make Codacy happy.
> BAU: Reformat README.md as per Codacy recommendations

- pom.xml
- src/test/java/uk/gov/pay/card/it/resources/CardIdResourceITest.java
Upgrade `rest-assured` library. See change log here https://raw.githubusercontent.com/rest-assured/rest-assured/master/changelog.txt
- CI should pass
> PP-4946 Upgrade rest-assured to v3.3.0

- Dockerfile
- Jenkinsfile
- pom.xml
- Upgrade to Java 11
- CI should pass
> PP-5048 - Migrate to Java 11

- src/main/java/uk/gov/pay/card/model/CardInformation.java
- src/main/java/uk/gov/pay/card/service/CardService.java
We can replace a static initialiser which sets up a `Map` with Java 9's `Map.of` construct.
Also, take the opportunity to make fields in `CardInformation` `final` and tidy away an unused import.
CI should save us here
> Use new Java features

- pom.xml
- src/main/java/uk/gov/pay/card/app/CardApi.java
- src/main/resources/config/config.yaml
- How should it be reviewed? 
- What feedback do you need? 
- If manual testing is needed, give suggested testing steps.
* Introduced any new environment variables / removed existing environment variable
* Added new API / updated existing API definition
> PP-5776: Configure server request logs to log in json format

- src/test/java/uk/gov/pay/card/it/resources/CardIdResourceITest.java
> PP-5782 update cardid data

- pom.xml
Reverts alphagov/pay-cardid#493
> Revert "Bump logging from 1.0.20201117103358 to 1.0.20201130170501"

- pom.xml
- src/main/resources/config/config.yaml
Update to latest version.
`stacktraceAppPackages` configuration option has become `inAppIncludes`
> PP-9093 Update dropwizard-sentry

- .github/workflows/_run-pact-provider-tests.yml
- .github/workflows/run-tests.yml
checked for Ubuntu 18.04 images and updated to ubuntu-latest.
> PP-10035 Updated ubuntu 18.04 to ubuntu-latest

- m1/arm64.Dockerfile
fixes an issue with the arm64 build process where some RUN commands were causing an error
> BAU fix arm64 build failure

- .gitignore
Use cardid data with new range for Stripe test card
Also added dependency-reduced-pom.xml to .gitignore
> PP-10428 Use new cardid data

- README.md
- pom.xml
- src/main/java/uk/gov/pay/card/app/CardApi.java
- src/main/java/uk/gov/pay/card/app/config/CardConfiguration.java
- src/main/resources/config/config.yaml
Remove graphite dependencies and config
Check build passes ok 🥳 
N/A
* ~Introduced any new environment variables /~ removed existing environment variable
* ~Added new API / updated existing API definition~
> PP-11228: Remove graphite metrics sending and config

- .gitmodules
- Change submodule URL to https as SSH agent is not configured in codebuild
> PP-10386 Change submodule URL to https

- .github/workflows/ci-trigger-release.yml
- m1/arm64.Dockerfile
- add concourse trigger-able release tag workflow
- clean apt cache on arm64 images
> PP-12111 image build source bin ranges from s3

- .github/workflows/post-merge.yml
> PP-12111 make `post-merge` workflow callable

- pom.xml
3.6.15 is no longer supported, upgrade to v4
> PP-9913 upgrade pact version

- pom.xml
Reverts alphagov/pay-cardid#1282
> Revert "Bump io.dropwizard:dropwizard-dependencies from 3.0.8 to 3.0.9"

- .github/dependabot.yml
- pom.xml
- src/main/java/uk/gov/pay/card/app/CardApi.java
- src/main/java/uk/gov/pay/card/app/config/CardConfiguration.java
- src/main/java/uk/gov/pay/card/model/CardInformationRequest.java
- src/main/java/uk/gov/pay/card/resources/CardIdResource.java
- src/main/java/uk/gov/pay/card/resources/HealthCheckResource.java
- src/main/resources/config/config.yaml
- src/test/java/uk/gov/pay/card/resources/HealthCheckResourceTest.java
Upgrade to use Dropwizard 4.
Also upgrade, what we can to Java Jakarta EE.
> PP-13652 upgrade modules to dropwizard 4

- pom.xml
- src/main/java/uk/gov/pay/card/app/CardApi.java
import `SentryAppenderFactory` from dropwizard-sentry.
> PP-13991 refactor to use vanilla SentryAppenderFactory
